//go:build linux
// +build linux

package main

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	cloudphoneNetworkPropPath = "/metadata/network.prop"
	cloudphoneEthernetIPDir   = "/data/misc/ethernet"
	cloudphoneEthernetIPFile  = "/data/misc/ethernet/ipconfig.txt"
)

// podIPItem matches status.podIPs JSON from Kubernetes downward API.
type podIPItem struct {
	IP string `json:"ip"`
}

// cloudphoneNetworkBootstrapBeforeInit writes /metadata/network.prop and optionally
// /data/misc/ethernet/ipconfig.txt (Java IpConfigStore v3) before exec /init.
// IPv6 is taken from POD_IPS JSON or from kernel (ip -6 addr) when present.
func cloudphoneNetworkBootstrapBeforeInit() {
	v4, prefix4 := cloudphoneResolveIPv4()
	gw4 := cloudphoneResolveGateway4(v4)
	dns := cloudphoneResolveDNS()
	v6, prefix6 := cloudphoneResolveIPv6()
	gw6 := cloudphoneResolveGateway6()

	if v4 == "" {
		fmt.Fprintf(os.Stderr, "run_container: cloudphone network bootstrap: no IPv4 (POD_IP / eth0), skip metadata\n")
		return
	}
	if prefix4 <= 0 {
		prefix4 = 32
	}

	_ = os.MkdirAll(filepath.Dir(cloudphoneNetworkPropPath), 0755)
	var prop strings.Builder
	prop.WriteString("# Generated by supervisord run_container before Android init; consumed by EthernetTracker (AOSP patch).\n")
	fmt.Fprintf(&prop, "cloudphone.network.ipv4=%s\n", v4)
	fmt.Fprintf(&prop, "cloudphone.network.ipv4.prefixlen=%d\n", prefix4)
	if gw4 != "" {
		fmt.Fprintf(&prop, "cloudphone.network.ipv4.gateway=%s\n", gw4)
	}
	if dns != "" {
		fmt.Fprintf(&prop, "cloudphone.network.dns=%s\n", dns)
	}
	if v6 != "" {
		if prefix6 <= 0 {
			prefix6 = 128
		}
		fmt.Fprintf(&prop, "cloudphone.network.ipv6=%s\n", v6)
		fmt.Fprintf(&prop, "cloudphone.network.ipv6.prefixlen=%d\n", prefix6)
		if gw6 != "" {
			fmt.Fprintf(&prop, "cloudphone.network.ipv6.gateway=%s\n", gw6)
		}
	}
	if err := os.WriteFile(cloudphoneNetworkPropPath, []byte(prop.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "run_container: write %s: %v\n", cloudphoneNetworkPropPath, err)
	}

	// Make POD_IPV6 visible to /init even when Kubernetes has no native POD_IPV6 field.
	if v6 != "" {
		_ = os.Setenv("POD_IPV6", v6)
	}

	if os.Getenv("CLOUDPHONE_SKIP_ETHERNET_IPCONFIG") == "1" || os.Getenv("CLOUDPHONE_SKIP_ETHERNET_IPCONFIG") == "true" {
		return
	}
	if gw4 == "" {
		gw4 = guessCiliumGatewayFromPodIP(v4)
	}
	if gw4 == "" {
		fmt.Fprintf(os.Stderr, "run_container: skip %s (no IPv4 gateway)\n", cloudphoneEthernetIPFile)
		return
	}
	ipc, err := buildJavaIpConfigStoreV3Eth0Static(v4, prefix4, gw4, dns)
	if err != nil {
		fmt.Fprintf(os.Stderr, "run_container: build ipconfig: %v\n", err)
		return
	}
	if err := os.MkdirAll(cloudphoneEthernetIPDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "run_container: mkdir %s: %v\n", cloudphoneEthernetIPDir, err)
		return
	}
	if err := os.WriteFile(cloudphoneEthernetIPFile, ipc, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "run_container: write %s: %v\n", cloudphoneEthernetIPFile, err)
	}
}

func cloudphoneResolveIPv4() (ip string, prefix int) {
	pod := strings.TrimSpace(os.Getenv("POD_IP"))
	if pod != "" {
		if strings.Contains(pod, "/") {
			ipStr, pfx, err := net.ParseCIDR(pod)
			if err == nil && ipStr.To4() != nil {
				return ipStr.String(), onesFromMask(pfx.Mask)
			}
		}
		if v := net.ParseIP(pod); v != nil && v.To4() != nil {
			// Infer prefix from eth0 if POD_IP is address-only
			if p := prefixFromIface4("eth0"); p > 0 {
				return v.String(), p
			}
			return v.String(), 32
		}
	}
	ipbin := resolveIPBinary()
	out, err := exec.Command(ipbin, "-4", "-o", "addr", "show", "dev", "eth0").CombinedOutput()
	if err != nil {
		return "", 0
	}
	line := strings.TrimSpace(string(out))
	fields := strings.Fields(line)
	for i, f := range fields {
		if f == "inet" && i+1 < len(fields) {
			parts := strings.Split(fields[i+1], "/")
			if len(parts) == 2 {
				prefix = atoiPositive(parts[1])
				return parts[0], prefix
			}
			return fields[i+1], 32
		}
	}
	return "", 0
}

func prefixFromIface4(dev string) int {
	ipbin := resolveIPBinary()
	out, err := exec.Command(ipbin, "-4", "-o", "addr", "show", "dev", dev).CombinedOutput()
	if err != nil {
		return 0
	}
	fields := strings.Fields(strings.TrimSpace(string(out)))
	for i, f := range fields {
		if f == "inet" && i+1 < len(fields) {
			parts := strings.Split(fields[i+1], "/")
			if len(parts) == 2 {
				return atoiPositive(parts[1])
			}
		}
	}
	return 0
}

func onesFromMask(m net.IPMask) int {
	if m == nil {
		return 0
	}
	o, _ := m.Size()
	return o
}

func atoiPositive(s string) int {
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			break
		}
		n = n*10 + int(c-'0')
	}
	if n <= 0 || n > 128 {
		return 0
	}
	return n
}

func cloudphoneResolveGateway6() string {
	if g := strings.TrimSpace(os.Getenv("POD_GATEWAY6")); g != "" {
		return g
	}
	ipbin := resolveIPBinary()
	out, err := exec.Command(ipbin, "-6", "route", "show", "default", "dev", "eth0").CombinedOutput()
	if err != nil {
		return ""
	}
	fs := strings.Fields(strings.TrimSpace(string(out)))
	for i, f := range fs {
		if f == "via" && i+1 < len(fs) {
			if net.ParseIP(fs[i+1]) != nil {
				return fs[i+1]
			}
		}
	}
	// Fallback to cni bootstrap snapshot (written before /init / netd).
	if g := strings.TrimSpace(readFileTrim(filepath.Join(cniBootstrapDir, "gateway6.txt"))); g != "" {
		if ip := net.ParseIP(g); ip != nil && ip.To4() == nil {
			return g
		}
	}
	// Last-resort fallback for Cilium style addresses in this cluster.
	if v6, _ := cloudphoneResolveIPv6(); v6 != "" {
		if g := guessCiliumGateway6FromPodIP(v6); g != "" {
			return g
		}
	}
	return ""
}

func cloudphoneResolveGateway4(v4 string) string {
	if g := strings.TrimSpace(os.Getenv("POD_GATEWAY")); g != "" {
		return g
	}
	ipbin := resolveIPBinary()
	out, err := exec.Command(ipbin, "-4", "route", "show", "default", "dev", "eth0").CombinedOutput()
	if err == nil {
		fs := strings.Fields(strings.TrimSpace(string(out)))
		for i, f := range fs {
			if f == "via" && i+1 < len(fs) {
				if net.ParseIP(fs[i+1]) != nil {
					return fs[i+1]
				}
			}
		}
	}
	out2, err2 := exec.Command(ipbin, "-4", "route", "show", "default").CombinedOutput()
	if err2 == nil {
		fs := strings.Fields(strings.TrimSpace(string(out2)))
		for i, f := range fs {
			if f == "via" && i+1 < len(fs) {
				if net.ParseIP(fs[i+1]) != nil {
					return fs[i+1]
				}
			}
		}
	}
	if v4 != "" {
		return guessCiliumGatewayFromPodIP(v4)
	}
	return ""
}

func cloudphoneResolveDNS() string {
	if d := strings.TrimSpace(os.Getenv("POD_DNS")); d != "" {
		return d
	}
	b, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return ""
	}
	var servers []string
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "nameserver ") {
			ns := strings.TrimSpace(strings.TrimPrefix(line, "nameserver "))
			if ns != "" && !strings.HasPrefix(ns, "127.") {
				servers = append(servers, ns)
			}
		}
		if len(servers) >= 4 {
			break
		}
	}
	return strings.Join(servers, ",")
}

func cloudphoneResolveIPv6() (ip string, prefix int) {
	if v := strings.TrimSpace(os.Getenv("POD_IPV6")); v != "" {
		if strings.Contains(v, "/") {
			ipStr, pfx, err := net.ParseCIDR(v)
			if err == nil && ipStr.To4() == nil {
				return ipStr.String(), onesFromMask(pfx.Mask)
			}
		}
		if v2 := net.ParseIP(v); v2 != nil && v2.To4() == nil {
			if p := prefixFromIface6("eth0"); p > 0 {
				return v2.String(), p
			}
			return v2.String(), 128
		}
	}
	raw := strings.TrimSpace(os.Getenv("POD_IPS"))
	if raw != "" {
		var items []podIPItem
		if err := json.Unmarshal([]byte(raw), &items); err == nil {
			for _, it := range items {
				a := net.ParseIP(strings.TrimSpace(it.IP))
				if a != nil && a.To4() == nil && !a.IsLoopback() && !a.IsLinkLocalUnicast() {
					if p := prefixFromIface6("eth0"); p > 0 {
						return a.String(), p
					}
					return a.String(), 128
				}
			}
		}
	}
	return cloudphoneIPv6FromKernel()
}

func prefixFromIface6(dev string) int {
	ipbin := resolveIPBinary()
	out, err := exec.Command(ipbin, "-6", "-o", "addr", "show", "dev", dev, "scope", "global").CombinedOutput()
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		for i, f := range fields {
			if f == "inet6" && i+1 < len(fields) {
				parts := strings.Split(fields[i+1], "/")
				if len(parts) == 2 {
					return atoiPositive(parts[1])
				}
			}
		}
	}
	return 0
}

func cloudphoneIPv6FromKernel() (ip string, prefix int) {
	ipbin := resolveIPBinary()
	out, err := exec.Command(ipbin, "-6", "-o", "addr", "show", "dev", "eth0", "scope", "global").CombinedOutput()
	if err != nil {
		return "", 0
	}
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		for i, f := range fields {
			if f == "inet6" && i+1 < len(fields) {
				parts := strings.Split(fields[i+1], "/")
				if len(parts) != 2 {
					continue
				}
				a := net.ParseIP(parts[0])
				if a == nil || a.To4() != nil || a.IsLoopback() {
					continue
				}
				pfx := atoiPositive(parts[1])
				if pfx <= 0 {
					pfx = 128
				}
				return a.String(), pfx
			}
		}
	}
	return "", 0
}

// buildJavaIpConfigStoreV3Eth0Static writes the same binary format as
// com.android.server.net.IpConfigStore (IPCONFIG_FILE_VERSION=3).
func buildJavaIpConfigStoreV3Eth0Static(ip string, prefix int, gateway string, dnsCSV string) ([]byte, error) {
	if net.ParseIP(ip) == nil || net.ParseIP(gateway) == nil {
		return nil, fmt.Errorf("invalid ip or gateway")
	}
	var buf bytes.Buffer
	if err := binary.Write(&buf, binary.BigEndian, int32(3)); err != nil { // IPCONFIG_FILE_VERSION
		return nil, err
	}
	writeJavaUTF(&buf, "ipAssignment")
	writeJavaUTF(&buf, "STATIC")
	writeJavaUTF(&buf, "linkAddress")
	writeJavaUTF(&buf, ip)
	if err := binary.Write(&buf, binary.BigEndian, int32(prefix)); err != nil {
		return nil, err
	}
	writeJavaUTF(&buf, "gateway")
	_ = binary.Write(&buf, binary.BigEndian, int32(0)) // default route
	_ = binary.Write(&buf, binary.BigEndian, int32(1)) // have gateway
	writeJavaUTF(&buf, gateway)
	for _, d := range strings.Split(dnsCSV, ",") {
		d = strings.TrimSpace(d)
		if d == "" || net.ParseIP(d) == nil {
			continue
		}
		writeJavaUTF(&buf, "dns")
		writeJavaUTF(&buf, d)
	}
	writeJavaUTF(&buf, "proxySettings")
	writeJavaUTF(&buf, "NONE")
	writeJavaUTF(&buf, "id")
	writeJavaUTF(&buf, "eth0")
	writeJavaUTF(&buf, "eos")
	return buf.Bytes(), nil
}

func writeJavaUTF(w *bytes.Buffer, s string) {
	if len(s) > 65535 {
		s = s[:65535]
	}
	_ = binary.Write(w, binary.BigEndian, uint16(len(s)))
	w.WriteString(s)
}
